# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrific', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='img_url',
            new_name='image',
        ),
    ]
